config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  root to: 'pages#home'
  
  devise_for :users,
    :path => '',
    :path_names => {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'signup'
    },
    :controllers => {
      sessions: "users/sessions",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      passwords: "users/passwords",
    }


  get "admin" => redirect("/admin/users"), as: :admin
  namespace :admin do
    resources :users, only: [:index, :show] do
      get :become, on: :member
    end
    mount Sidekiq::Web, at: "/sidekiq"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


  def full_name
    [first_name, last_name].join(" ")
  end
  
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController

    http_basic_authenticate_with name: "admin", password: "password"
    
    layout "admin"
    
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController

    before_action :get_user, only: [:show]

    def index
      @users = User.order(created_at: :desc)
    end

    def show
    end

    def become
      sign_in(:user, User.find(params[:id]), { :bypass => true })
      redirect_to root_path
    end

    private

    def get_user
      @user = User.find_by(id: params[:id])
      redirect_to users_admin_index_path unless @user
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_raven_context

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    root_path
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  def destroy
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password) }
  end

  def after_sign_up_path_for(resource)
    flash[:success] = "We have sent a confirmation email to your inbox. Verify your email address to get started."
    root_path 
  end

  def after_inactive_sign_up_path_for(resource)
    flash[:success] = "We have sent a confirmation email to your inbox. Verify your email address to get started."
    root_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    super
  end

  protected

  def after_sign_in_path_for(resource)
    flash[:success] = "Welcome back #{resource.first_name}!"
    root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <div class="page-header">
        <h1>Users</h1>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created at</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |u| %>
            <tr>
              <td><%= u.id %></td>
              <td><%= link_to u.full_name, admin_user_path(u.id) %></td>
              <td><%= u.email %></td>
              <td><%= u.created_at.strftime("%d %b,%Y") %></td>
              <td><%= link_to "Become user", become_admin_user_path(u.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <div class="page-header">
        <div class="row">
          <div class="col-md-12">
            <h1><%= link_to "Become user", become_admin_user_path(@user.id), class: "btn btn-default pull-right" %> <%= @user.full_name %>  <small class="text-muted"><%= @user.email %></small></h1>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=1024, maximum-scale=1.0">
  <title>Admin Area</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Menu</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Admin Area", admin_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= "active" if request.path.match(admin_users_path) %>"><%= link_to "Users", admin_users_path %></li>
          <li><%= link_to "Sidekiq Web", '/admin/sidekiq/busy?poll=true' %></li>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% page_title = @page_title ? "#{@page_title} - #{ENV['APP_NAME']}" : "#{ENV['APP_NAME']} - #{ENV['APP_DESCRIPTION']}" %>
    <title><%= page_title %></title>

    <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
    <link rel="apple-touch-icon" href="/favicon.png"/>

    <!-- Viewport meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="<%= ENV['APP_NAME'] %>">

    <!-- OpenGraph Meta -->
    <meta property="og:site_name" content="<%= ENV['APP_NAME'] %>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:description" content="<%= ENV['APP_DESCRIPTION'] %>"/>
    <meta property="og:url" content="<%= ENV['APP_URL'] %>"/>
    <meta property="og:title" content="<%= page_title %>"/>
    <meta property="og:image" content="<%= ENV['APP_IMAGE'] %>"/>

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="<%= ENV['TWITTER'] %>" />
    <meta name="twitter:title" content="<%= page_title %>" />
    <meta name="twitter:description" content="<%= ENV['APP_DESCRIPTION'] %>" />
    <meta name="twitter:image" content="<%= ENV['APP_IMAGE'] %>" />

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/scripts/ga' %>

  </head>

  <body class="bg-gray-200">
    <%= yield %>

    <%= render 'layouts/scripts/flash' %>
    <%= yield :extra_scripts %>
  </body>
</html>

app/views/layouts/scripts/_flash.html.erb
<script type="text/javascript">
<% if flash[:success] %>
  showSuccess("<%= flash[:success] %>");
<% end %>
<% if flash[:notice] %>
  showNotice("<%= flash[:notice] %>");
<% end %>
<% if flash[:warning] %>
  showWarning("<%= flash[:warning] %>");
<% end %>
<% if flash[:error] %>
  showError("<%= flash[:error] %>");
<% end %>
</script>

app/views/layouts/scripts/_form_errors.html.erb
<% if obj.errors.any? %>
  <script type="text/javascript">
    showError("<%= j render(:partial => 'layouts/scripts/validation', :locals => {:obj => obj}) %>")
  </script>
<% end %>

app/views/layouts/scripts/_ga.html.erb
<% if (analytics = ENV['GA_ID']).present? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= analytics %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '<%= analytics %>');

    document.addEventListener('turbolinks:load', event => {
    if (typeof gtag === 'function') {
      gtag('config', '<%= analytics %>', {
        'page_location': event.data.url
      });
    }
  });
  </script>
<% end %>

app/views/layouts/scripts/_validation.html.erb
<% if obj.errors.any? %>
  <div class="error_explanation">
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="h-screen flex justify-center items-center">
  <div class="w-1/2 p-16 rounded-lg bg-white shadow-lg">
    
    <h1 class="text-4xl font-black">Welcome!</h1>
    
    <p class="text-gray-700 text-xl">
      This is a <a href="https://github.com/ManuelFrigerio/rails-blueprint" target="_blank" class="text-gray-900 underline">Rails <%= Rails.version %> app boilerplate</a> by <a href="https://manuel.friger.io" target="_blank" class="text-gray-900 underline">Manuel Frigerio</a>
    </p>
    <div class="mt-6">
      <% if user_signed_in? %>
        <%= link_to "Log out".html_safe, destroy_user_session_path, method: :delete, class: "bg-red-300 rounded-lg border py-2 px-5 border-red-400 text-red-700" %>
      <% else %>
        <%= link_to "Signup", new_user_registration_path, class: "btn" %>
        <%= link_to "Login", new_user_session_path, class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<div class="mt-6 text-sm text-gray-500">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name), class: "text-gray-500" %> •
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name), class: "text-gray-500" %> •
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name), class: "text-gray-500" %> •
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation email?", new_confirmation_path(resource_name), class: "text-gray-500" %>
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "text-gray-500" %> •
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "text-gray-500" %> •
    <% end -%>
  <% end -%>
</div>